/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.dataMovieController;
import javax.swing.JTable;
import javax.swing.JTextField;
import model.modelTableDataMovie;
import model.dataMovie;

/**
 *
 * @author Zainur Fadli
 */
public class MainView extends javax.swing.JFrame {

    /**
     * Creates new form MainView
     */
    dataMovieController dc;
    public MainView() {
        initComponents();
        JTxt_idHidden.setVisible(false);
        dc = new dataMovieController(this);
        dc.isiTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataMovie = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        JTxt_judul = new javax.swing.JTextField();
        JTxt_alur = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTxt_penokohan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTxt_akting = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jbtn_tambah = new javax.swing.JButton();
        jbtn_update = new javax.swing.JButton();
        jbtn_delete = new javax.swing.JButton();
        jbtn_clear = new javax.swing.JButton();
        JTxt_idHidden = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableDataMovie.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tableDataMovie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataMovieMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDataMovie);

        jLabel1.setText("Judul");

        JTxt_judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxt_judulActionPerformed(evt);
            }
        });

        JTxt_alur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxt_alurActionPerformed(evt);
            }
        });

        jLabel2.setText("Alur");

        JTxt_penokohan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxt_penokohanActionPerformed(evt);
            }
        });

        jLabel3.setText("Penokohan");

        JTxt_akting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxt_aktingActionPerformed(evt);
            }
        });

        jLabel4.setText("Akting");

        jbtn_tambah.setText("Tambah");
        jbtn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_tambahActionPerformed(evt);
            }
        });

        jbtn_update.setText("Update");
        jbtn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_updateActionPerformed(evt);
            }
        });

        jbtn_delete.setText("Delete");
        jbtn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_deleteActionPerformed(evt);
            }
        });

        jbtn_clear.setText("Clear");
        jbtn_clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_clearActionPerformed(evt);
            }
        });

        JTxt_idHidden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTxt_idHiddenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTxt_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(JTxt_alur, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(JTxt_penokohan, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(JTxt_akting, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_clear)
                            .addComponent(jbtn_delete)
                            .addComponent(jbtn_update)
                            .addComponent(jbtn_tambah))
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(JTxt_idHidden, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(JTxt_idHidden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTxt_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTxt_alur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTxt_penokohan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTxt_akting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jbtn_tambah)
                .addGap(18, 18, 18)
                .addComponent(jbtn_update)
                .addGap(18, 18, 18)
                .addComponent(jbtn_delete)
                .addGap(18, 18, 18)
                .addComponent(jbtn_clear)
                .addContainerGap(47, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTxt_judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxt_judulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxt_judulActionPerformed

    private void JTxt_alurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxt_alurActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxt_alurActionPerformed

    private void JTxt_penokohanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxt_penokohanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxt_penokohanActionPerformed

    private void JTxt_aktingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxt_aktingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxt_aktingActionPerformed

    private void jbtn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_tambahActionPerformed
        // TODO add your handling code here:
        dc.insert();
        dc.isiTabel();
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil ditambah!", "Informasi", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        dc.clear();
    }//GEN-LAST:event_jbtn_tambahActionPerformed

    private void tableDataMovieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataMovieMouseClicked
        int baris = tableDataMovie.getSelectedRow();
        modelTableDataMovie model = (modelTableDataMovie) tableDataMovie.getModel();
        dataMovie selectedMovie = model.getDataMovieAt(baris);
        int id = selectedMovie.getId();

        JTxt_judul.setText(selectedMovie.getJudul());
        JTxt_alur.setText(String.valueOf(selectedMovie.getAlur()));
        JTxt_penokohan.setText(String.valueOf(selectedMovie.getPenokohan()));
        JTxt_akting.setText(String.valueOf(selectedMovie.getAkting()));
        JTxt_idHidden.setText(String.valueOf(selectedMovie.getId()));

    }//GEN-LAST:event_tableDataMovieMouseClicked

    private void jbtn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_updateActionPerformed
        // TODO add your handling code here:
        dc.update();
        dc.isiTabel();
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil diupdate!", "Informasi", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        dc.clear();
    }//GEN-LAST:event_jbtn_updateActionPerformed

    private void JTxt_idHiddenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTxt_idHiddenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTxt_idHiddenActionPerformed

    private void jbtn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_deleteActionPerformed
        // TODO add your handling code here:
        dc.delete();
        dc.isiTabel();
        javax.swing.JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Informasi", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        dc.clear();
    }//GEN-LAST:event_jbtn_deleteActionPerformed

    private void jbtn_clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_clearActionPerformed
        // TODO add your handling code here:
        dc.clear();
    }//GEN-LAST:event_jbtn_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTxt_akting;
    private javax.swing.JTextField JTxt_alur;
    private javax.swing.JTextField JTxt_idHidden;
    private javax.swing.JTextField JTxt_judul;
    private javax.swing.JTextField JTxt_penokohan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_clear;
    private javax.swing.JButton jbtn_delete;
    private javax.swing.JButton jbtn_tambah;
    private javax.swing.JButton jbtn_update;
    private javax.swing.JTable tableDataMovie;
    // End of variables declaration//GEN-END:variables

    public JTable getTableDataMovie() {
        return tableDataMovie;
    }

    public void setTableDataMovie(JTable tableDataMovie) {
        this.tableDataMovie = tableDataMovie;
    }

    public JTextField getJTxt_akting() {
        return JTxt_akting;
    }

    public void setJTxt_akting(JTextField JTxt_akting) {
        this.JTxt_akting = JTxt_akting;
    }

    public JTextField getJTxt_alur() {
        return JTxt_alur;
    }

    public void setJTxt_alur(JTextField JTxt_alur) {
        this.JTxt_alur = JTxt_alur;
    }

    public JTextField getJTxt_judul() {
        return JTxt_judul;
    }

    public void setJTxt_judul(JTextField JTxt_judul) {
        this.JTxt_judul = JTxt_judul;
    }

    public JTextField getJTxt_penokohan() {
        return JTxt_penokohan;
    }

    public void setJTxt_penokohan(JTextField JTxt_penokohan) {
        this.JTxt_penokohan = JTxt_penokohan;
    }
    
    public javax.swing.JTextField getJTxt_idHidden() {
        return JTxt_idHidden;
    }

    
    
    
}
